# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'ia-production-subcription(66748fac-619c-4aa8-af04-423f39287a51)'
    appName: 'wa-document-host-prod-westeurope-001'
    containers: 'ia-library'
    multicontainerConfigFile: '/Dockerfile'
