# Cloud build yaml

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/infinity-arc/support-docs:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/infinity-arc/support-docs:latest','gcr.io/infinity-arc/support-docs:$BUILD_ID']
images: [
  'gcr.io/infinity-arc/support-docs:latest',
  'gcr.io/infinity-arc/support-docs:$BUILD_ID'
]